#!/usr/bin/env python3
"""Generate the encrypted vault secrets header consumed by behavior_vault.c.

Reads plaintext passwords from the macOS Keychain and encrypts them with a key
derived from a master passphrase via PBKDF2-HMAC-SHA256. Keychain account and
service list come from the environment (VAULT_ACCOUNT, VAULT_SERVICES) so no
personal identifiers live in this source. VAULT_SERVICES is comma-separated and
its order maps to the &vault <index> bindings. VAULT_ACCOUNT defaults to the OS
user. Iteration count: VAULT_KDF_ITERS (default 50000).

  key      = PBKDF2-HMAC-SHA256(passphrase, salt, iters)[0:16]   (shared)
  verifier = PBKDF2-HMAC-SHA256(passphrase, salt, iters)[16:20]
  per secret: nonce (random); keystream_i = SHA256(key || nonce || u32le(i));
              ciphertext = plaintext XOR keystream

Only ciphertext, salt, verifier and the iteration count reach the firmware, so
strength rests on passphrase entropy against an offline PBKDF2 attack.
"""

import getpass
import hashlib
import os
import struct
import sys

HID_USAGE_KEY = 0x07
MOD_LSFT = 0x02
DEFAULT_ITERS = 3000

_SHIFT_SPECIAL = {
    '!': 0x1E, '@': 0x1F, '#': 0x20, '$': 0x21, '%': 0x22,
    '^': 0x23, '&': 0x24, '*': 0x25, '(': 0x26, ')': 0x27,
    '_': 0x2D, '+': 0x2E, '{': 0x2F, '}': 0x30, '|': 0x31,
    ':': 0x33, '"': 0x34, '~': 0x35, '<': 0x36, '>': 0x37, '?': 0x38,
}
_PLAIN_SPECIAL = {
    ' ': 0x2C, '\n': 0x28, '\t': 0x2B,
    '-': 0x2D, '=': 0x2E, '[': 0x2F, ']': 0x30, '\\': 0x31,
    ';': 0x33, "'": 0x34, '`': 0x35, ',': 0x36, '.': 0x37, '/': 0x38,
}


def account():
    return os.environ.get("VAULT_ACCOUNT") or getpass.getuser()


def services():
    raw = os.environ.get("VAULT_SERVICES", "")
    return [s.strip() for s in raw.split(",") if s.strip()]


def iters():
    return int(os.environ.get("VAULT_KDF_ITERS", DEFAULT_ITERS))


def char_to_id_mods(ch):
    if ch.islower():
        return (0x04 + (ord(ch) - ord('a')), 0)
    if ch.isupper():
        return (0x04 + (ord(ch) - ord('A')), MOD_LSFT)
    if ch.isdigit():
        return (0x27 if ch == '0' else 0x1E + (int(ch) - 1), 0)
    if ch in _PLAIN_SPECIAL:
        return (_PLAIN_SPECIAL[ch], 0)
    if ch in _SHIFT_SPECIAL:
        return (_SHIFT_SPECIAL[ch], MOD_LSFT)
    raise ValueError(f"unsupported password character: {ch!r}")


def encode_char(ch):
    usage_id, mods = char_to_id_mods(ch)
    return (mods << 24) | (HID_USAGE_KEY << 16) | usage_id


def plaintext_for(password):
    return b"".join(struct.pack("<I", encode_char(c)) for c in password)


def keystream(key, nonce, length):
    out = bytearray()
    i = 0
    while len(out) < length:
        out += hashlib.sha256(key + nonce + struct.pack("<I", i)).digest()
        i += 1
    return bytes(out[:length])


def derive(passphrase, salt, n):
    dk = hashlib.pbkdf2_hmac("sha256", passphrase.encode(), salt, n, dklen=20)
    return dk[:16], dk[16:20]


def encrypt_secret(password, key):
    nonce = os.urandom(16)
    pt = plaintext_for(password)
    ct = bytes(a ^ b for a, b in zip(pt, keystream(key, nonce, len(pt))))
    return nonce, ct


def c_array(data):
    return ", ".join(f"0x{b:02x}" for b in data) or "0"


def emit(salt, verifier, n, secrets):
    print("#pragma once")
    print("/* Generated by syspass_gen.py. Contains only ciphertext. Do not commit. */")
    print(f"#define VAULT_SECRET_COUNT {len(secrets)}")
    print(f"#define VAULT_KDF_ITERS {n}")
    print(f"static const uint8_t vault_salt[16] = {{{c_array(salt)}}};")
    print(f"static const uint8_t vault_verifier[4] = {{{c_array(verifier)}}};")
    print("static const struct vault_secret vault_secrets[VAULT_SECRET_COUNT] = {")
    for nonce, ct in secrets:
        print("    {")
        print(f"        .nonce = {{{c_array(nonce)}}},")
        print(f"        .ct_len = {len(ct)},")
        print(f"        .ct = {{{c_array(ct)}}},")
        print("    },")
    print("};")


def placeholder(count):
    return bytes(16), bytes(4), DEFAULT_ITERS, [(bytes(16), b"") for _ in range(count)]


def main():
    svcs = services()
    if os.environ.get("VAULT_GEN_PLACEHOLDER"):
        n = len(svcs) or int(os.environ.get("VAULT_PLACEHOLDER_COUNT", "3"))
        emit(*placeholder(n))
        return

    if not svcs:
        sys.stderr.write("syspass_gen: set VAULT_SERVICES (comma-separated), e.g. in config/vault.local\n")
        sys.exit(1)

    import keyring
    acct = account()
    passwords = [keyring.get_password(s, acct) for s in svcs]
    if not any(passwords):
        sys.stderr.write("syspass_gen: no keychain entries found, emitting placeholders\n")
        emit(*placeholder(len(svcs)))
        return

    passphrase = os.environ.get("VAULT_PIN")
    if passphrase is None:
        passphrase = getpass.getpass("vault passphrase> ")
        if passphrase != getpass.getpass("confirm passphrase> "):
            sys.stderr.write("syspass_gen: passphrases do not match, nothing generated\n")
            sys.exit(1)
    if not passphrase:
        sys.stderr.write("syspass_gen: passphrase must not be empty\n")
        sys.exit(1)

    n = iters()
    salt = os.urandom(16)
    key, verifier = derive(passphrase, salt, n)

    secrets = []
    for service, pw in zip(svcs, passwords):
        if pw is None:
            sys.stderr.write(f"syspass_gen: '{service}' missing, placeholder used\n")
            secrets.append((bytes(16), b""))
        else:
            secrets.append(encrypt_secret(pw, key))
    emit(salt, verifier, n, secrets)


if __name__ == "__main__":
    main()
